language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: firebase
  token:
    secure: encrypted_firebase_CI_token
  project: react-test-4feb1
env:
  global:
  - secure: wG+QNj5rgBomWi++9wjosT1coga27SXS9gF+oI6FlE4Q7V2Ad1e/cIGEZEptlJBFkW/40LB9H/6vs/RTwbUMLZJbQi8pzY58FkWxbI/yikGBGLxfBLYByg6ZO8rQZ80yEUB/zORbHUQOOpKVueZp4R6wlP50KlkANKNeoIplssGpjgXDV6J80K0LmKatpv0OFID+fsqbpqLm3viIQF01qOpUA/9ZBBta1Y/MHbtRgPXKJOgAxPtW6jTCUUbyukShQidL1requGPitIwzRNG9QLa4wJgA25KII8/t+wHXGS3aasNKus8IEeAvIjlFW81HR9UF+19gMptbIf0Ai8Qpk4CEbXPgdMrpqSdPLJm1v9x6FSM3NYo4qJ94kKqD/Y4DR0O5pAEkDSB/XMHmmFgKrK6zAwOTVSUm+ZiceLs9ERs0lEo+u1eLqvk/WVMFWBsZeVQiXSIl3uGisidlGgyE0bwosO6bOZ/NY4UnABdasWQ/3MBiy/ESAHNFQLl+fMbzVvd40LG6e9DUxwmaGSwnCR8nwVmsI23bgfMQV6x0x0ICefGV5su0MsdyAaJAbkifxYznCEz9Jg3hhTI0mqjlHaCy4so49X4J1CAzElv581yBDEYjMIugjS0ZhR3WFrTljZGy2kALxmNVRG8KESpK7uYI9jmokd+r4GB9keWUjhY=
  - secure: IL/jjs3nluW4UB6KP8AQnBNjPEO0KHn5B+Nf760B/BdIMKh7aqT6Y6/fnxfXT5yhw3vXMJsOU0+b6XNsOgiXXXwjgwyJGN9G3RqyUTdpseuOI4/l1XOsmetIiRf8LzgVEGFqLFOW3U4FjEP+ZYQDOfhJtsEfjiaZD6kbJa0MC1mckaBfiV7kQZIffbdGhuOm75UYAyucxXTtPe3vgps12bWap0667ewVvUTptaA9o3Zwl7dJFRK8lbEyvmOZcw+Y6RtAqU0o9OcCRK0G8MMmwr1k28qEM7YHfvdKE96rrzcYYP2RsCk75ymgFnnxB6hmdEqq72HdZY7az6hFoyl8PJrmr8RwasgOrRxWNDQWJflY+gqDIskRA32MRIU4U2vywZ7FOpKcejYDgvQUvj2qhFW2pBNyTxc3xbuF917PmkDSbR7N59Ls4Gd1+ElL9gHE5dglqpNgjN2F8DpObJdnTcjOWKm4Ugs5FQgpTEwC+CTDwQRiw2R6OXHGa3ZIUkOli3x3il9nMgM+q5nD7moCrcfZAOmfrm6Bnq8/eR//oqegv8MxIgGipGPYOFBpZcRRs4aQWixffYN2JHR3cLzEuds8mmzaHDyC9E26rzZAU2/mQ2Zs+O+C3yezQ5zqkRvad8+npckCuNCKeO45Si2IPOw63kiq55b+BQGISSqkK1c=
