language: node_js
node_js:
- "10.12"
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: firebase
  token:
    secure: aZ9V8gB8BW48Xgv1d5Ze951+bhBFMyArq2uveOeMPdOIssBBc/T/FTis8Qj/dJEOJQNurPPUi4FcnkEchHNXGIOpsOfbOgg+10nVMgN6smVI3P1TjYnspna8Aaz8Rah28vEnT+xcIHGESOLV4eHgcNbfhrTlLMgKPFdc3Jz1XJhoIR8jpBb7Z1z6BcDN53VaU9kFum4suoB+cfEyZPt8a/ISxNlwvmqTnNQ55bwXSgJsVWwYiFXH9iRu1ShezPWm7WnIOyfRx+bGtaSsJP0o+F6k67Rf595W+eHKrjQ9VqS1VH3rU4SilSTkaL1ri4PPj0oMDDTADLexQ6uzrkM2WqlC6uIevxXotedgkva8CU8u6oGY6fO3NLUCpken455EkbbI6cn+pZrJG76iOBncagTf8qYQemTOWnFMUG2YMcu8IHRhfpLVHTTB9QmRSD8pib9kv5JW9V5FNbKy9B+q8FhHmZPJqWzeRt2ntew10e3+30qUdR+Ld142N5GvOihYXRTEToNEaPMVW7kwA9jCwvBvv35c7d1GWSTDdAnU2X3VmlP/kIwnf9jFIadV41hJTL0GyJZzym3k+Fv7lO5x1v74S8N8GU85G+VNEdow6ZPMqj6tiAIq0gq1Wu48iChipKf99pskFh9e/a3plwFQYMrv1L3uIliSsUZeFOOH1Nk=
  project: react-test-4feb1